### ISSUE TITLE
Complete support for text serde

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb-std#122]
1. Allow all data types (consignment, index-related and stash-related) to be exported as text-based serde formats (YAML, TOML, JSON)
2. Make these representations efficient (display large strict types libraries as bindle-encoded data, display AluVM code as disassembly, display all 32-hashes or blinding factors as Baid58 or hex strings

**Comment by zoedberg** [comment]
@dr-orlovsky is support for JSON and TOML still planned? From what I've seen to support those we should do big changes to the consignment structure (i.e. remove maps with non-string keys), therefore I propose to drop that idea and close this issue since support for YAML has been completed

**Comment by dr-orlovsky** [comment]
I agree. We can live just with YAML, at least for now
