### ISSUE TITLE
Create interfaces to allow external access to the values inside the Allocation.

### ISSUE THREAD

**Issue by EthanShang8989** [RGB-WG/rgb-std#128]
I am filtering Allocation inside rgb21 from inside contractIface.data.state. tried to extract the data inside but found it to be private.
Suggest to expose the interface.
pub struct Allocation(TokenIndex, OwnedFraction);
```
impl Allocation {
    pub fn with(index: TokenIndex, fraction: OwnedFraction) -> Allocation {
        Allocation(index, fraction)
    }
    pub fn token_id(self) -> TokenIndex { self.0 }
    pub fn fraction(self) -> OwnedFraction { self.1 }
}
```

**Comment by crisdut** [comment]
Done in #127

**Comment by dr-orlovsky** [comment]
Closing since the fixing PR is already merged
