### ISSUE TITLE
Multiple data states to same assignment (seal)

### ISSUE THREAD

**Issue by crisdut** [RGB-WG/rgb-std#130]
Hi @dr-orlovsky, 

I would like to share a strange behavior during my tests with [UDC](https://github.com/RGB-WG/rgb-schemata/pull/24).

In the contract creation step, I am adding two different allocations to the same seal because the UDC allows one or many tokens in the contract. 

However, I could not do this because the Builder stores the allocation data in a hashmap, using the seal as the key. That is, the last allocation always overwrites the first.

This is a particular case for UDC because this does not occur in other contracts, as fungibles, because we add a single value.

I considered modifying the Builder to support a set of data states instead of a single data state per seal.

What do you think?

**Comment by dr-orlovsky** [comment]
I think we can utilize seal blinding factor to generate distinct seals for the same UTXO

**Comment by crisdut** [comment]
> I think we can utilize seal blinding factor to generate distinct seals for the same UTXO

Ok, great! 

I will trying implement this ideia in the next week.

**Comment by dr-orlovsky** [comment]
I am closing the issues since I believe that the seals must always have a distinct blinding, and thus this is a non-issue and rather an answered question. If there were no way to create seals with different blinding, that would be a bug and you would be welcome to open a new issue for that bug.
