### ISSUE TITLE
invoice creation with transports fails

### ISSUE THREAD

**Issue by nicbus** [RGB-WG/rgb-std#131]
Trying to create an invoice containing transport endpoints I get the following error:
```
InvalidInvoice { details: "invalid query parameter invalid transport .." }
```

The invoice string looks like:
```
rgb:RMLihGM-c1rQxBy5n-pkobrwMkL-4yXH6nGR9-HFHQKkqnw-mGbtez/RGB25/69+bcrt:utxob:2WdCeAu-MSNxt4ivz-H9BXHkGcv-fw1phiJ2v-JTHCdW9m1-5xJ8aqp?expiry=1705411284&endpoints=,rpc://127.0.0.1:3000/json-rpc
```

I guess that `endpoints=,rpc://127.0.0.1:3000/json-rpc` cannot be parsed because of the empty value before the comma and that this happens because `RgbInvoiceBuilder::new()` creates the `RgbInvoice` with `transports` set to `vec![RgbTransport::UnspecifiedMeans]`, which is then rendered to an empty string.

The `add_transport` and `add_transports` methods just add the provided transport(s) to the vector, leaving the initial `RgbTransport::UnspecifiedMeans` in place.

I am not sure what the proper fix should be (i.e. removing the existing `UnspecifiedMeans` before adding new transports?).

@dr-orlovsky what's your idea about it?

Once we agree on a fix I can take care of the implementation and open a PR.

**Comment by dr-orlovsky** [comment]
I think you are right about why this does happen.

Removing the existing UnspecifiedMeans before adding new transports should be the correct fix
