### ISSUE TITLE
Prefix for invoice state types

### ISSUE THREAD

**Issue by crisdut** [RGB-WG/rgb-std#133]
**Description**

I'm working on non-fungible support for invoices, and I think we need to add a prefix to identify the type of invoice state.

For example:

```
# Suggestion 1: For amounts
rgb:(..)/RGB20/amount:100+bc:utxob:egXsFnw-5Eud7WKYn-7DVQvcPbc-rR69YmgmG-veacwmUFo-uMFKFb

# Suggestion 2: For general data
rgb:(..)/RGB21/data:0000000100000001+bc:utxob:egXsFnw-5Eud7WKYn-7DVQvcPbc-rR69YmgmG-veacwmUFo-uMFKFb

# Suggestion 3: For specific data (For example, RGB21 interface token allocation)
rgb:(..)/RGB21/allocation:0000000100000001+bc:utxob:egXsFnw-5Eud7WKYn-7DVQvcPbc-rR69YmgmG-veacwmUFo-uMFKFb
```

What do you think?

Thanks

**Comment by cryptoquick** [comment]
I think Maxim has suggested that this follow RFC 3986 URI format, so perhaps a better format is:

```
# Suggestion 1: For amounts
rgb:(..)/RGB20/?amount=100&bc=utxob:egXsFnw-5Eud7WKYn-7DVQvcPbc-rR69YmgmG-veacwmUFo-uMFKFb

# Suggestion 2: For general data
rgb:(..)/RGB21/?data=0000000100000001&bc=utxob:egXsFnw-5Eud7WKYn-7DVQvcPbc-rR69YmgmG-veacwmUFo-uMFKFb

# Suggestion 3: For specific data (For example, RGB21 interface token allocation)
rgb:(..)/RGB21/?allocation=0000000100000001&bc=utxob:egXsFnw-5Eud7WKYn-7DVQvcPbc-rR69YmgmG-veacwmUFo-uMFKFb
```

**Comment by crisdut** [comment]
> I think Maxim has suggested that this follow RFC 3986 URI format, so perhaps a better format is:
> 
> ```
> # Suggestion 1: For amounts
> rgb:(..)/RGB20/?amount=100&bc=utxob:egXsFnw-5Eud7WKYn-7DVQvcPbc-rR69YmgmG-veacwmUFo-uMFKFb
> 
> # Suggestion 2: For general data
> rgb:(..)/RGB21/?data=0000000100000001&bc=utxob:egXsFnw-5Eud7WKYn-7DVQvcPbc-rR69YmgmG-veacwmUFo-uMFKFb
> 
> # Suggestion 3: For specific data (For example, RGB21 interface token allocation)
> rgb:(..)/RGB21/?allocation=0000000100000001&bc=utxob:egXsFnw-5Eud7WKYn-7DVQvcPbc-rR69YmgmG-veacwmUFo-uMFKFb
> ```

Humm.. the prefix "bc" is not a parameter, but the new format of the seal, and amount/data is like a path parameter.  I think we can define state_format as optional parameter, see below:

```
# Suggestion 3: For specific data (For example, RGB21 interface token allocation)
rgb:(..)/RGB21/0000000100000001+bc:utxob(...)?state_type=allocation
```

**Comment by crisdut** [comment]
I only saw this comment now, after I responded to the PR review about invoice.

Well, I'll update it to follow your comments, ok?
