### ISSUE TITLE
PresistedState typo

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb-std#138]
I'm not sure but the enum `PresistedState` looks like a typo, I guess it should be `PersistedState`. @dr-orlovsky

**Comment by dr-orlovsky** [comment]
It is a typo indeed! It took me few minutes to see the actual difference :)

**Comment by zoedberg** [comment]
fix in 71e67ac3ee2455ba86fd69405c217c471d3f8cb3
