### ISSUE TITLE
Fieldname vs Typename in the ExtensionIface

### ISSUE THREAD

**Issue by cymqqqq** [RGB-WG/rgb-std#160]
Should we change fieldname to typename in ExtensionIface in iimpl.rs?
<img width="466" alt="image" src="https://github.com/RGB-WG/rgb-std/assets/8555534/4a2a11bc-2f64-444b-b2e5-91aef0ad1d36">
<img width="433" alt="image" src="https://github.com/RGB-WG/rgb-std/assets/8555534/15d195e4-e60d-41cf-b2b1-5a3dfc48dfc3">
For this:
<img width="459" alt="image" src="https://github.com/RGB-WG/rgb-std/assets/8555534/dc94eb55-ce4e-431a-8fa2-dcde9d313370"><img width="423" alt="image" src="https://github.com/RGB-WG/rgb-std/assets/8555534/c42057e7-c3ad-4681-a835-d0ff57cc605f">

**Comment by dr-orlovsky** [comment]
Not sure I exactly understood your question, but with https://github.com/RGB-WG/rgb-std/pull/162 we will move to using `FieldName` instead of `TypeName` for transition and extensions name
