### ISSUE TITLE
Invalid Consignment ID Parse

### ISSUE THREAD

**Issue by crisdut** [RGB-WG/rgb-std#164]
**Description**

Hi @dr-orlovsky , 

I found some issues related with the latest [PR](https://github.com/RGB-WG/rgb-std/pull/161), when I trying retrieve a contract string using `Contract::from_str`. 

When we convert **Contract** to **string**, the **consignmentId** is not generated with prefix "con", see below:

```
-----BEGIN RGB CONSIGNMENT-----
Id: urn:lnp-bp:consignment:HdAmNh-t7YeDLsn-vgRpyKEa-sDhsVVEt-U3Sh7nQt-vQwKcn#vatican-value-support
Version: v2
Type: contract
Contract-Id: rgb:gKW294J-661grYv28-fefSyCsN6-A2WjaFLMa-cTMeUonSr-HUiJa1
Checksum-SHA256: cdd29f25ce1c3f4bdad20f0c35b94955d646402e6e20a11b5376ee60cae3166a\n\n0ssM^565gFSPIWXgR!k`%j9m@+1P_4+Ax*F<@u}
(...)
-----END RGB CONSIGNMENT-----
"
``` 

But when we retrieve the Contract from the same string representation, the prefix **con** is added, see below:

```
con:consignment:HdAmNht7YeDLsnvgRpyKEasDhsVVEtU3Sh7nQtvQwKcn#vatican-value-support
```

And when we try parse baid58 from string, The [code](https://github.com/UBIDECO/rust-baid58/blob/master/src/lib.rs#L470-L496)  cannot two prefix ("con", "consignment") and three suffix ("vatican", "value", "support"), and the error occurs:

```
InvalidId(Unparsable("con:consignment:HdAmNht7YeDLsnvgRpyKEasDhsVVEtU3Sh7nQtvQwKcn#vatican-value-support"))
```

I hope this help

Thanks

**Comment by crisdut** [comment]
Hi @dr-orlovsky,

Just a update:

Maybe the problem if generated ID without prefix is [here](https://github.com/UBIDECO/ascii-armor/blob/master/src/lib.rs#L288).  Could we assume that every armor ID must be baid58 ?

If so, I believe that if we can call `to_baid58_sttring` instead of `to_string`, the problem disappears.

**Comment by Gigi3d** [comment]
Great place to be!
