### ISSUE TITLE
spending change fails (v0.11 and script-refactor branches)

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb-std#189]
Using `v0.11` and `script-refactor` branches on rgb-lib and `v0.11` branch on the CLI (cannot use `script-refactor` there since https://github.com/RGB-WG/rgb/issues/169), I'm encountering an error when trying to spend an RGB change.

Specifically what I'm doing is (all with opret first):
- issuing a NIA asset on wallet1
- sending some assets from wallet1 to wallet2 (blinded)
- again sending some assets from wallet1 to wallet2 (blinded)

The second transfer fails at consignment creation time with the error:
```
the provided state transition is not a part of the bundle
```
which comes from rgb-std.

**Comment by dr-orlovsky** [comment]
I need three data files (stash, state and index) and consignments to debug...

**Comment by dr-orlovsky** [comment]
I found a reason. Please check https://github.com/RGB-WG/rgb-std/commit/cca830fb0aaee62633b95ec51686fb873a826e86

**Comment by zoedberg** [comment]
Issue has been fixed, closing this. @dr-orlovsky please rebase `script-refactor` on top of this so I can continue debugging from there

**Comment by dr-orlovsky** [comment]
done
