### ISSUE TITLE
accepting transfer spending RGB change fails

### ISSUE THREAD

**Issue by nicbus** [RGB-WG/rgb-std#194]
Using commit `f9813b7` plus a cargo update to include rgb-std #193 and trying to execute 2 consecutive transfers, I face an issue.

This is what I'm doing (wallet 1 is the issuer/sender, wallet 2 is the recipient):
- issue a NIA asset on wallet 1
- sending some assets from wallet 1 to wallet 2
- sending some more assets (spending RGB change) from wallet 1 to wallet 2

The 2nd transfer fails when trying to accept it with:
```
Error: index already contains information about bundle d0dd9f86be169ec70e6d3041f1fda0dfe4e65da46327d1d4121771589fa2f6af which specifies witness bc:f58173072ef1c98148bfe60ebb281f5bb4f90dbc3d9b6540a95d641f8884a9fa instead of witness bc:f58173072ef1c98148bfe60ebb281f5bb4f90dbc3d9b6540a95d641f8884a9fa.                    
It may happen due to RGB standard library bug, or indicate internal stash inconsistency and compromised stash data storage.
```

**Comment by nicbus** [comment]
Re-tested after a cargo update to include commit https://github.com/RGB-WG/rgb-std/commit/5084eb2f9244102a263d1b23d66fb1c5c61cfa7c (part of https://github.com/RGB-WG/rgb-std/pull/193) and the transfer spending the change now succeeds.

**Comment by dr-orlovsky** [comment]
@zoedberg waiting for your confirmation that your issue is also fixed

**Comment by zoedberg** [comment]
Fixed, thank you
