### ISSUE TITLE
witness beneficiary not embedding close method

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb-std#198]
During Viareggio meeting we reported that the `WitnessVout` beneficiary doesn't embed the desired close method. It was said that this is a bug because a receiver should be able to decide this. Currently it's up to the sender to decide which close method to use in that case.

@dr-orlovsky I think we should fix this before 0.11 preview release

**Comment by dr-orlovsky** [comment]
Thank you for not forgetting!
