### ISSUE TITLE
Possible misuse of method `fluent_uri::Path::segments`

### ISSUE THREAD

**Issue by yescallop** [RGB-WG/rgb-std#208]
Hi, the maintainers of `rgb-std`. I'm the author of `fluent-uri`. I notice that this repo contains code calling the method `fluent_uri::Path::segments`: https://github.com/RGB-WG/rgb-std/blob/9e23bd272a989c5f0315f458565abfe3c1f7b2a0/invoice/src/parse.rs#L333-L337

Which might not work as intended. It currently accepts both absolute and rootless paths, for example `/foo/bar` and `foo/bar`.

Whether this behavior is intended or not, I think I should expand the method's documentation so that it's less likely to be misused. I have changed it to the following: https://github.com/yescallop/fluent-uri-rs/blob/db4cde70754126cdc75425fefd655d1c88904a82/src/encoding/mod.rs#L382-L414

Thanks for depending on my crate `fluent-uri` and I'll continue to make sure it offers a good user experience.

As an aside, I find that the following code looks a bit strange on line 274: https://github.com/RGB-WG/rgb-std/blob/9e23bd272a989c5f0315f458565abfe3c1f7b2a0/invoice/src/parse.rs#L268-L277

It might not work as intended as I imagine the `rgb:` prefix should be written in both branches, or I could be wrong since I don't know much about the project. Still, I bring this up just in case.

**Comment by dr-orlovsky** [comment]
Dear @yescallop! Thank you very much for taking time reviewing our code and writing such a detailed fix proposal!

**Comment by dr-orlovsky** [comment]
BTW you are right about the needed check on whether the path is absolute. I did a PR here: https://github.com/RGB-WG/rgb-std/pull/209

As for the `rgb:` prefix in the second suggestion, everything is correct since in the first branch it is printed as a part of `ContractId` `Display` implementation
