### ISSUE TITLE
latest code compiles bug

### ISSUE THREAD

**Issue by cymqqqq** [RGB-WG/rgb-std#236]
I pull the latest code, which includes the refactor of the `fs` module,  then I run the `cargo  build` command, and the errors print out:
<img width="600" alt="image" src="https://github.com/user-attachments/assets/66832d45-3497-42c8-9b04-c096a28c8471">
Do I need to checkout the other branch?

**Comment by dr-orlovsky** [comment]
Fixed at latest commits to the master
