### ISSUE TITLE
Interface resolves to an "abstract" interface out of inheritance hierarchy

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb-std#263]
In the interface wrappers there are panics raised when trying to read a contract with the incorrect interface (e.g. https://github.com/RGB-WG/rgb-interfaces/blob/master/src/rgb20/wrapper.rs#L86). These panics have broken a method in rgb-lib, where we get a contract ID and a contract interface and we verify that the user has provided the correct iface (e.g. doing `let contract = runtime.contract_iface_class::<Rgb20>(contract_id);`). @dr-orlovsky please suggest a workaround for this or remove the panic

**Comment by dr-orlovsky** [comment]
As I suggested in the beginning, the panic helped to find a real bug: `Stash::impl_for::<C>` instead of error `NoAbstractImpl` somehow resolves to an implementation of RGB20 for RGB21 interface...
