### ISSUE TITLE
sender has incorrect view of allocations when TX has 0 confirmations

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb-std#270]
As shown by the `accept_0conf` test in https://github.com/RGB-WG/rgb-integration-tests/pull/5 there's an issue on the sender's allocations when a TX has 0 confirmations. The sender after a transfer which has not been mined sees 2 allocations (the issued amount and the change amount) instead of just 1 (the change amount)

**Comment by dr-orlovsky** [comment]
I believe this is a non-issue and must be handled by the wallet UX: https://github.com/RGB-WG/rgb-tests/pull/5#issuecomment-2357924607

**Comment by zoedberg** [comment]
I agree, closing this
