### ISSUE TITLE
history: RGB change doesn't show up

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb-std#282]
When calling the wallet history APIs, the RGB change doesn't show up.

**Comment by dr-orlovsky** [comment]
What do you mean by "change"? History shows just operations, and there is no such thing as "change operation". Do you mean that the last operation in the history is not shown - or something else?

**Comment by zoedberg** [comment]
I mean that after a wallet sends some RGB assets it will see the operation with the sent amount but no operation for the change amount.

**Comment by dr-orlovsky** [comment]
But there must be no operation with a change amount since the change is not an operation at all!

**Comment by zoedberg** [comment]
I thought a change should appear as an operation with `OpDirection::Received`, but probably I misunderstood the desired behavior of the history API.

Not sure it's related to this (I thought so but I'm not sure anymore): running the `send_to_oneself` test (introduced in https://github.com/RGB-WG/rgb-tests/pull/3) with the updated code you'll see only the issued operation after the send. Is this the intended behavior?

**Comment by dr-orlovsky** [comment]
> Is this the intended behavior?

Yes. History is for humans, meaning they need to see incoming and outgoing funds, not self-transfers or change
