### ISSUE TITLE
Add contract operation history API

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb-std#94]
Reconstruction of RGB contract operation history is currently impossible with the existing API; instead wallets have to keep the history by themselves constructing it with the operation flow. For multi-device wallet that requires a special wallet synchronization service in addition to just running an RGB Node-like solution.

RGB Std Lib can provide an API which may return a reconstructed history by iterating underlying RGB operations. It can be that the optimal will be to keep that history as a part of the inventory.

**Comment by zoedberg** [comment]
@dr-orlovsky hasn't this been completed?

**Comment by dr-orlovsky** [comment]
Correct. closing
