### ISSUE TITLE
Add a way to track taptweaks

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb-std#98]

**Comment by crisdut** [comment]
About this topic, today I use rgbwallet provide by `rgb-contract` crates.

I made some changes to work:

First, I created this to extract commitment from psbt:
https://github.com/diba-io/bitmask-core/blob/development/src/rgb/psbt.rs#L327-L352

Then, I make this change to work with result of the extract_commit above:
https://github.com/crisdut/rgb/commit/38e5cc172b5ca418ff637566ced2350877045788

I hope it help you with some ideas.

**Comment by dr-orlovsky** [comment]
Closing, since v0.11 already does that
