### ISSUE TITLE
add support for deterministic entropy

### ISSUE THREAD

**Issue by zoedberg** [RGB-WG/rgb-std#99]
In order to use RGB in LN we need to remove any type of entropy in transfers, so that channel counterparties can reconstruct RGB anchors in a deterministic way.

Right now in our [rgb-lightning-sample](https://github.com/RGB-Tools/rgb-lightning-sample) we just duplicated methods with entropy, renamed them in `<original_method_name>_static` and changed the entropy fields to a fixed number. But ideally, for better privacy, this fixed number should be configurable via the method, so that the channel counterparties can derive this number via some secret channel data.

[Here](https://github.com/RGB-Tools/rgb-wallet/compare/v0.10.3...static_0.10) you can see the methods we had to duplicate (`dbc_conclude` -> `dbc_conclude_static` and `add_raw_state` -> `add_raw_state_static`).

**Comment by dr-orlovsky** [comment]
Related: https://github.com/RGB-WG/rgb-std/issues/111#issuecomment-1872514299

**Comment by zoedberg** [comment]
This has been completed, so closing it
